---

- name: Check if powertools is enabled
  lineinfile:
    state: absent
    path: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
    regexp: ^enabled=0
  check_mode: true
  changed_when: false
  register: powertools_disabled
  tags: epel

- name: Make sure powertools repo is enabled
  command: dnf config-manager --set-enabled powertools
  args:
    warn: no
  when: powertools_disabled.found == 1
  tags: epel

- name: Make sure EPEL repo files are installed
  dnf:
    name: ["epel-release", "epel-next-release"]
    state: present
  tags: epel
